package:
  name: tcl
  version: 8.6.1

source:
  fn: tcl8.6.1-src.tar.gz
  url: http://prdownloads.sourceforge.net/tcl/tcl8.6.1-src.tar.gz
  md5: aae4b701ee527c6e4e1a6f9c7399882e 

about:
  home: http://www.tcl.tk/ 
  license: tcltk
