package:
  name: simplegeneric
  version: 0.8.1

source:
  fn: simplegeneric-0.8.1.zip
  url: https://pypi.python.org/packages/source/s/simplegeneric/simplegeneric-0.8.1.zip
  md5: f9c1fab00fd981be588fc32759f474e3 

test:
  imports:
    - simplegeneric

requirements:
  build:
    - setuptools
  run:
    - setuptools

about:
  home: http://cheeseshop.python.org/pypi/simplegeneric
  license: ZPL-2.1
