package:
  name: libffi
  version: 3.0.13

source:
  fn:  libffi-3.0.13.tar.gz 
  url: ftp://sourceware.org/pub/libffi/libffi-3.0.13.tar.gz 
  md5: 45f3b6dbc9ee7c7dfbbbc5feba571529

about:
  home: http://sourceware.org/libffi/ 
  license: MIT
