package:
  name: nose
  version: 1.3.0

source:
  fn: nose-1.3.0.tar.gz 
  url: https://pypi.python.org/packages/source/n/nose/nose-1.3.0.tar.gz
  md5: 95d6d32b9d6b029c3c65674bd9e7eabe 

requirements:
  build:
    - setuptools
    - coverage
  run:
    - setuptools
    - coverage

about:
  home: http://nedbatchelder.com/code/coverage 
  license: BSD
