package:
  name: cython
  version: 0.19.1

source:
  fn: Cython-0.19.1.tar.gz
  url: http://www.cython.org/release/Cython-0.19.1.tar.gz 
  md5: df4cfb2b8e3345272e3fc451b76bd630

requirements:
  build:
    - python
  run:
    - python

about:
  home: http://www.cython.org
  license: Apache-2.0
