CPPFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA  -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE6"
CPPFLAGS="${CPPFLAGS} -DSQLITE_ENABLE_RTREE -DSQLITE_SOUNDEX  -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_SECURE_DELETE -DSQLITE_CHECK_PAGES -DSQLITE_CORE"
export CPPFLAGS
./configure --prefix="$PREFIX" \
	--enable-threadsafe \
	--enable-readline \
	--disable-static
make -j4
make install HAVE_TCL=0
