package:
  name: matplotlib
  version: 1.3.0

source:
  fn: matplotlib-1.3.0.tar.gz
  url: https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.3.0/matplotlib-1.3.0.tar.gz 
  md5: 139e1157a3e641fa6270d667a2088458

requirements:
  build:
    - setuptools
    - freetype
    - numpy
    - libpng
    - six
    - nose
    - pyparsing
    - python-dateutil
    - pytz
  run:
    - python
    - freetype
    - numpy
    - libpng
    - six
    - nose
    - pyparsing
    - python-dateutil
    - pytz

about:
  home: http://matplotlib.org/
  license: matplotlib BSD

