package:
  name: readline
  version: 6.2.4

source:
  fn:  readline-6.2.tar.gz
  url: ftp://ftp.cwru.edu/pub/bash/readline-6.2.tar.gz
  md5: 67948acb2ca081f23359d0256e9a271c
  patches:
     - readline62-001
     - readline62-002
     - readline62-003
     - readline62-004
     - readline-5.0-no_rpath.patch
     - readline-5.2-no-ignore-shlib-errors.patch

about:
  home: http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL-3

requirements:
  build:
    - ncurses
  run:
    - ncurses
