package:
  name: pyparsing
  version: 1.5.7

source:
  fn: pyparsing-1.5.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pyparsing/pyparsing-1.5.7.tar.gz
  md5: 9be0fcdcc595199c646ab317c1d9a709

about:
  home: http://nedbatchelder.com/code/coverage 
  license: MIT
