package:
  name: python-dateutil
  version: 2.1

source:
  fn: python-dateutil-2.1.tar.gz
  url: https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.1.tar.gz
  md5: 1534bb15cf311f07afaa3aacba1c028b

requirements:
  build:
    - six
    - setuptools
  run:
    - six
    - setuptools

about:
  home: http://labix.org/python-dateutil 
  license: MIT
