package:
  name: pytz
  version: 2013d

source:
  fn: pytz-2013d.tar.gz
  url: https://pypi.python.org/packages/source/p/pytz/pytz-2013d.tar.gz
  md5: ee090b586c792bcf393c84dd0a75c9b5

requires:
   build:
      - setuptools
   run:
      - setuptools

about:
  home: http://pytz.sourceforge.net
  license: MIT
