package:
  name: pygments
  version: 1.6

source:
  fn: Pygments-1.6.tar.gz
  url: https://pypi.python.org/packages/source/P/Pygments/Pygments-1.6.tar.gz
  md5: a18feedf6ffd0b0cc8c8b0fbdb2027b1

requirements:
  build:
    - setuptools

  run:
    - setuptools

test:
  imports:
    - pygments

about:
  home: http://pygments.org/
  license: BSD License
