package:
  name: pyzmq
  version: 13.1.0

source:
  fn: pyzmq-13.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pyzmq/pyzmq-13.1.0.tar.gz
  md5: b54a2209a4efed93ed00282d949db8d9

requirements:
  build:
    - python
    - zeromq

  run:
    - python
    - zeromq

test:
  imports:
    - zmq

about:
  home: http://github.com/zeromq/pyzmq
  license: BSD License or GNU Library or Lesser General Public License (LGPL)
