package:
  name: cmake
  version: 2.8.11.1

source:
  fn: cmake-2.8.11.1.tar.gz
  url: http://www.cmake.org/files/v2.8/cmake-2.8.11.1.tar.gz
  md5: df5324a3b203373a9e0a04b924281a43

test:
  commands:
    - cmake --help

about:
  home: http://www.cmake.org/
  license: BSD

requirements:
  build:
    - zlib
    - bzip2
  run:
    - zlib
    - bzip2
