package:
  name: zlib
  version: 1.2.8

source:
  fn: zlib-1.2.8.tar.gz
  url: http://zlib.net/zlib-1.2.8.tar.gz
  md5: 44d667c142d7cda120332623eab69f40 

about:
  home: http://www.zlib.net
  license: ZLIB
